homepage:
  url: https://www.sfdph.org/dph/EH/Food/Score/default.asp





documentation:

  - url: https://www.sfdph.org/dph/EH/Food/Score/Violation.asp
    title: Description of Violations

  - url: https://www.sfdph.org/dph/EH/Food/Inspections.asp
    title: About inspections

  - url: http://library.amlegal.com/nxt/gateway.dll/California/health/article8foodandfoodproducts?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca
    title: San Francisco Health Code, Article 8

  - url: http://2015.padjo.org/briefs/data_notes/sql-explore-sf-restaurant-data/
    title: Using SQL to explore restaurant data

  - url: https://extxfer.sfdph.org/food/File%20Specifications.pdf
    title: Schema/File specifications
    localref: documentation/file-schema-specifications.pdf




articles:
  - url: https://www.sfgate.com/food/article/San-Francisco-restaurants-failed-health-10874533.php
    title: These San Francisco restaurants failed health inspections recently
    date: 2018-01-30
    source: SFGate

